version: '3'

volumes:
  postgres_volume:

services:
  db:
    image: postgres:16.0-alpine3.18
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    restart: on-failure
    depends_on:
      - db
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - migrations